stages:
  - lint
  - test
  - pre-build
  - build
  - deploy

variables:
  POETRY_VERSION: 1.8.2  # Remplace par la version correcte
  REGISTRY_URL: ${CI_REGISTRY}  # Utilise le registry GitLab CI/CD
  IMAGE_NAME: "$REGISTRY_URL/hello-world-ci"

lint:
  stage: lint
  image: python:3.10
  tags:
    - walnut
  script:
    - pip install poetry==$POETRY_VERSION
    - poetry install
    - poetry run black --check .
    - poetry run pylint main.py || true  # Ignore les warnings

test:
  stage: test
  image: python:3.10
  tags:
    - walnut
  script:
    - pip install poetry==$POETRY_VERSION
    - poetry install
    - poetry run pytest

pre-build:
  stage: pre-build
  image: alpine
  tags:
    - walnut
  script:
    - if [ ! -f Dockerfile ]; then echo "Dockerfile missing!"; exit 1; fi

build:
  stage: build
  image: docker:latest
  tags:
    - walnut
  services:
    - docker:dind
  before_script:
    - echo "Nettoyage de REGISTRY_URL"
    - export REGISTRY_URL=$(echo $REGISTRY_URL | sed 's|https://||' | sed 's|/$||')
  script:
    - docker build -t $IMAGE_NAME:latest .

deploy:
  stage: deploy
  image: docker:latest
  tags:
    - walnut
  services:
    - docker:dind
  before_script:
    - echo "Nettoyage de REGISTRY_URL"
    - export REGISTRY_URL=$(echo $REGISTRY_URL | sed 's|https://||' | sed 's|/$||')
  script:
    - echo "$DOCKER_PASSWORD" | docker login "$REGISTRY_URL" -u "$DOCKER_USERNAME" --password-stdin
    - docker push $IMAGE_NAME:latest