stages:
  - lint
  - test
  - build
  - deploy

variables:
  REGISTRY_URL: "$CI_REGISTRY"
  IMAGE_NAME: "$CI_REGISTRY/hello-world-ci"

before_script:
  - apt-get update && apt-get install -y curl
  - pip install poetry

lint:
  stage: lint
  image: python:3.10
  tags:
    - walnut
  script:
    - poetry install
    - poetry run black --check .
    - poetry run pylint src/ || true

test:
  stage: test
  image: python:3.10
  tags:
    - walnut
  script:
    - poetry install
    - poetry run pytest

build:
  stage: build
  image: docker:latest
  tags:
    - walnut
  services:
    - docker:dind
  script:
    - if [ ! -f Dockerfile ]; then echo "Dockerfile is missing!"; exit 1; fi
    - export REGISTRY_URL=$(echo "$REGISTRY_URL" | sed 's|https://||' | sed 's|/$||')
    - echo "Using registry: $REGISTRY_URL"
    - docker build -t "$REGISTRY_URL/hello-world-ci:latest" .

deploy:
  stage: deploy
  image: docker:latest
  tags:
    - walnut
  services:
    - docker:dind
  script:
    - echo "$REGISTRY_PASSWORD" | docker login "$REGISTRY_URL" -u "$REGISTRY_LOGIN" --password-stdin
    - docker push "$REGISTRY_URL/hello-world-ci:latest"