name: Auto Create Pull Request

on:
  push:
    branches:
      - '*'         # Triggers the workflow for all branches
      - '!master'   # Excludes the main branch (master)

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract branch name
        id: extract_branch
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Install GitHub CLI
        run: sudo apt-get install gh -y

      - name: Verify GitHub CLI
        run: gh --version

      - name: Check for existing PR
        id: check_pr
        env:
          GH_TOKEN: ${{ secrets.GHUB_TOKEN }}
        run: |
          PR_TITLE="Auto PR: ${{ env.branch }}"
          PR_EXISTS=$(gh pr list --json title -q ".[].title" 2>/dev/null | grep -c "\"$PR_TITLE\"")
          echo "PR_EXISTS=$PR_EXISTS" >> $GITHUB_ENV

      - name: Create Pull Request
        if: env.PR_EXISTS == 0
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GHUB_TOKEN }}
          commit-message: "Auto PR from branch ${{ env.branch }}"
          title: "Auto PR: ${{ env.branch }}"
          body: |
            This is an automated pull request created from the branch `${{ env.branch }}`.
          branch: ${{ env.branch }}
          base: master  # Replace with 'main' if that's your main branch
          draft: false  # Change to true if you want to create a draft PR